# Generated by Django 4.2.4 on 2023-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'guardian'), (3, 'organizer'), (4, 'admin')], default=1),
        ),
    ]
