# Generated by Django 4.2.4 on 2024-01-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_admins', 'Can add admins'), ('change_admins', 'Can change admins'), ('delete_admins', 'Can delete admins'), ('view_admins', 'Can view admins'), ('add_organizers', 'Can add organizers'), ('change_organizers', 'Can change organizers'), ('delete_organizers', 'Can delete organizers'), ('view_organizers', 'Can view organizers')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
