# Generated by Django 4.2.4 on 2024-01-18 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_custom_groups_and_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
