# Generated by Django 4.2.4 on 2024-02-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
