version: '3.1'

services:

  db:
    image: postgres:16
    container_name: koala-db
    restart: always
    environment:
      POSTGRES_USER: koala
      POSTGRES_PASSWORD: koala
      POSTGRES_DB: koaladb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: