# Generated by Django 4.2.4 on 2024-02-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdpr', models.BooleanField(default=False)),
                ('parental_consent', models.BooleanField(default=False)),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='files', related_query_name='files', to='files.file')),
            ],
        ),
    ]
