# Generated by Django 4.2.4 on 2024-02-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdpr',
            old_name='gdpr',
            new_name='gdpr_consent',
        ),
    ]
