# Generated by Django 4.2.4 on 2024-03-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0002_rename_gdpr_gdpr_gdpr_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdpr',
            name='files',
        ),
    ]
