# Generated by Django 4.2.4 on 2024-01-23 22:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('street', models.CharField(max_length=63)),
                ('postcode', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('city', models.CharField(max_length=63)),
                ('school_type', models.PositiveSmallIntegerField(choices=[(1, 'Podstawowa'), (2, 'Ponadpodstawowa')], default=1)),
                ('accepted', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('confirmation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.school')),
                ('team_members', models.ManyToManyField(blank=True, null=True, related_name='team_members', related_query_name='team_member', to=settings.AUTH_USER_MODEL)),
                ('team_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.teamtutor')),
            ],
        ),
    ]
