# Generated by Django 4.2.4 on 2024-01-24 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Wprowadź prawidłowy kod pocztowy w formacie 12-345', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
