# Generated by Django 4.2.4 on 2024-01-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('dashboard', '0003_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtutor',
            name='confirmation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
