# Generated by Django 4.2.4 on 2024-02-14 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_teamguardian_remove_team_team_tutor_delete_teamtutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='guardians',
            field=models.ManyToManyField(blank=True, null=True, related_name='guardians', related_query_name='guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
