# Generated by Django 4.2.4 on 2024-03-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('dashboard', '0007_school_guardians'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='files.file'),
        ),
    ]
