# Generated by Django 4.2.4 on 2024-04-03 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='guardians',
            field=models.ManyToManyField(blank=True, null=True, related_name='schools', related_query_name='guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
