# Generated by Django 4.2.4 on 2024-05-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_school_guardians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teamguardian'),
        ),
    ]
