# Generated by Django 4.2.4 on 2024-05-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_path'),
        ('dashboard', '0011_alter_team_team_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamguardian',
            name='confirmation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
    ]
